### ISSUE TITLE
Chroma crashes on Beat Saber ver. 1.24.0

### ISSUE THREAD

**Issue by Oct2Pup** [bsq-ports/Chroma#20] opened 2022-08-17 16:08 UTC
Every time I try to enable Chroma Beat Saber crashes.
It does start to load and shows the BS logo and then it crashes, this repeats until the Oculus Quest 2 shows a notification that it crashed multiple times.
If Chroma is disabled there is no issue at all.
I read about some issues running NoodleEx and Chroma at the same time, so I tried them both individually.
First I tried to disable other mods I am using to see if that changed anything, but sadly that is not the case.
I'm running BS version 1.24.0 and the core mods works perfectly.

I am not the only one experiencing this issue, my friend who also got the Oculus Quest 2 running the same BS version experiences the same thing when Chroma is enabled.
We have two different models of the Quest 2 but that shouldn't matter as the only difference is the 64 GB storage on his VR headset and 128 GB on mine.

I hope this is enough information to be taken seriously or then ask, and I will try to provide more details ;-)

**Comment by Fernthedev** [comment] 2022-08-17 16:22
Duplicate of #18
This is the same issue with more words. I would prefer actual data such as logs.

I cannot reproduce the issue either, nor do the majority of the userbase excluding you or your friend therefore I cannot take this as an actual issue without a sizeable sample size if data is not being provided. 

Quest model, software version or storage size do not impact (in any way I'm aware) the quest installation process or modloader setup, therefore they're not considered as important variables in cause of "crash".

BS 1.24 is supported with some minor bugs but they're not crashes at startup. If you're using non-release builds, such as Github Actions or redistributed builds, you're probably on your own unless you share the data required to diagnose said issue. 

Even if logs are provided, if the log is deemed unreadable or containing no useful data the issue will be closed as an infinite amount of variables can cause the issue that is seemingly not widespread.

Finally, instead of opening new duplicate issues, just reopen #18 
Consider going to BSMG's quest-help Discord channel if you need help making the mods or installation work rather than use the `Github Issues` channel to ask for help. I use this channel strictly for bug reports that can be reproduced or realistically solved.

**Closed by Fernthedev** 2022-08-17 16:22 UTC

**Comment by Oct2Pup** [comment] 2022-08-17 16:47
I am not a programmer, so please tell me how I can obtain the logs you will need to look into this issue
