### ISSUE TITLE
1.28 final score issue

### ISSUE THREAD

**Issue by pieguy744** [bsq-ports/Chroma#48] opened 2023-05-03 19:52 UTC
When either Noodle or Chroma is enabled on Beatsaber 1.28, all final scores will display as either S or SS depending on the actual score, if it's a C or Less, then the player will receive an S, and C or higher, an SS will be received. Reports of this bug from the following Reddit posts:

https://www.reddit.com/r/beatsaber/comments/12j5jat/score_glitch/

https://www.reddit.com/r/beatsaber/comments/12a6qs8/beat_saber_final_score_rank_not_correct/

https://www.reddit.com/r/beatsaber/comments/136wus6/does_anybody_have_any_bug_help_with_quest_128_on/

**Comment by Fernthedev** [comment] 2023-05-03 19:53
Duplicate of StackDoubleFlow/CustomJSONData#34

**Closed by Fernthedev** 2023-05-03 19:53 UTC
