### ISSUE TITLE
Game Crash (With Logs)

### ISSUE THREAD

**Issue by BoogieHasFun** [bsq-ports/Chroma#2] opened 2021-08-20 21:13 UTC
[Chroma_2_4_10q1.log](https://github.com/bsq-ports/Chroma/files/7024135/Chroma_2_4_10q1.log)

**Comment by Fernthedev** [comment] 2021-08-20 21:14
Please post the tombstone or `adb logcat` logs

**Comment by BoogieHasFun** [comment] 2021-08-20 21:15
I have no idea how to get those logs.

**Comment by Fernthedev** [comment] 2021-08-20 21:16
tombstone would be in the parent directory of the logs you uploaded right now. Feel free to upload all 3

**Comment by BoogieHasFun** [comment] 2021-08-20 21:18
ima put that on a mediafire link because github wont let me post the files

**Comment by BoogieHasFun** [comment] 2021-08-20 21:19
https://www.mediafire.com/folder/abr2xc60pmbxh/logs

**Comment by Fernthedev** [comment] 2021-08-20 21:24
This crash indicates custom json data is giving wrong information. Please try reinstall the qmod or game

**Comment by BoogieHasFun** [comment] 2021-08-20 21:54
Did both, maybe other mods?
Or maybe just the song I'm playing doesn't work with this mod, (the map changes block colors)

**Comment by Fernthedev** [comment] 2021-08-20 22:08
Please send the map then

**Comment by BoogieHasFun** [comment] 2021-08-20 22:09
https://beatsaver.com/maps/bb27

**Comment by Fernthedev** [comment] 2021-08-20 22:43
I am unable to reproduce the crash. I will be closing this, you may try this [though](https://github.com/bsq-ports/Chroma/releases/tag/2.4.10q2).

**Closed by Fernthedev** 2021-08-20 22:43 UTC

**Comment by BoogieHasFun** [comment] 2021-08-20 22:46
also looks like some mods mess up pinkcore pinkcore, chroma might be the mod that causes this.

**Comment by Fernthedev** [comment] 2021-08-20 22:47
I can assure you Chroma is not the cause of PinkCore bugs, at least not directly.

**Comment by BoogieHasFun** [comment] 2021-08-20 23:00
chroma turns off the names on the song with pinkcore, im pretty sure pinkcore is messing things up or the other way around

**Comment by jakearchibald** [comment] 2021-08-21 16:58
> chroma turns off the names on the song (eg. Chroma Map [Player], but [Player] isnt there) with pinkcore

I'm experiencing the same thing, then a crash at the start of each song. I'll try uninstalling and reinstalling.

**Comment by Fernthedev** [comment] 2021-08-23 16:25
Looking at the crash, it seems to resemble #4. The fix is already implemented though waiting merge at StackDoubleFlow/CustomJSONData#9. Wait patiently :)
