### ISSUE TITLE
Bug with Chroma

### ISSUE THREAD

**Issue by Oct2Pup** [bsq-ports/Chroma#19] opened 2022-08-17 15:47 UTC
Every time I try to enable Chroma Beat Saber crashes, if disabled there is no issue at all.
I'm on BS version 1.24.0

**Comment by Fernthedev** [comment] 2022-08-17 15:48
Duplicate of #18
While that is slightly more information, it still means as much as the previous issue.

**Closed** 2022-08-17 15:48 UTC
